# Generated by Django 5.2.6 on 2025-09-09 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("node_host", models.CharField(max_length=128)),
                ("active", models.BooleanField(default=True)),
                ("auth_token", models.CharField(default="", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Container",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=128)),
                ("container_id", models.CharField(max_length=64, unique=True)),
                ("base_image", models.CharField(default="", max_length=128)),
                ("first_start", models.BooleanField(default=False)),
                (
                    "memory_mb",
                    models.PositiveIntegerField(
                        default=256, help_text="memory for the container"
                    ),
                ),
                (
                    "vcpus",
                    models.PositiveIntegerField(
                        default=2, help_text="CPU for the container"
                    ),
                ),
                (
                    "disk_gib",
                    models.PositiveIntegerField(default=10, help_text="disk in gb"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="created", max_length=32)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="containers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_node",
                        to="vm_manager.node",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResourceQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_containers",
                    models.PositiveIntegerField(
                        default=1, help_text="Max number of alive containers"
                    ),
                ),
                (
                    "max_memory_mb",
                    models.PositiveIntegerField(
                        default=256, help_text="Max memory per container MB"
                    ),
                ),
                (
                    "vcpus",
                    models.PositiveIntegerField(
                        default=2, help_text="Max CPU per container VCPU"
                    ),
                ),
                (
                    "ai_use_per_day",
                    models.PositiveIntegerField(
                        default=5, help_text="Daily request for the AI"
                    ),
                ),
                (
                    "default_disk_gib",
                    models.PositiveIntegerField(default=10, help_text="Max disk in gb"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Resource quota user",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FileTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=512)),
                ("content", models.TextField(blank=True, default="")),
                ("mode", models.PositiveIntegerField(default=420)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="vm_manager.filetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "path"),
                "unique_together": {("template", "path")},
            },
        ),
    ]
