# Generated by Django 5.2.6 on 2025-09-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vm_manager", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="base_image",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="container",
            name="first_start",
            field=models.BooleanField(default=True),
        ),
    ]
