# Generated by Django 5.2.5 on 2025-09-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vm_manager", "0002_alter_container_base_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="desired_state",
            field=models.CharField(
                choices=[("running", "running"), ("stopped", "stopped")],
                default="running",
                help_text="Desired state for reconciliation",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="arch",
            field=models.CharField(
                default="",
                help_text="Host architecture (e.g., x86_64, aarch64)",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="capacity_mem_mb",
            field=models.PositiveIntegerField(
                default=1024, help_text="Total host memory in MB"
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="capacity_vcpus",
            field=models.PositiveIntegerField(default=1, help_text="Total host vCPUs"),
        ),
        migrations.AddField(
            model_name="node",
            name="healthy",
            field=models.BooleanField(
                default=False, help_text="Did the node respond correctly?"
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="heartbeat_at",
            field=models.DateTimeField(
                blank=True, help_text="Last heartbeat received", null=True
            ),
        ),
        migrations.AddField(
            model_name="node",
            name="kvm_available",
            field=models.BooleanField(
                default=False, help_text="Whether /dev/kvm is available"
            ),
        ),
        migrations.AlterField(
            model_name="container",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "created"),
                    ("provisioning", "provisioning"),
                    ("running", "running"),
                    ("stopped", "stopped"),
                    ("error", "error"),
                ],
                default="created",
                help_text="Current status",
                max_length=32,
            ),
        ),
    ]
