# Generated by Django 5.2.6 on 2025-09-19 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vm_manager", "0003_container_desired_state_node_arch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="resource_quota",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="containers",
                to="vm_manager.resourcequota",
            ),
        ),
    ]
