# Generated by Django 5.2.6 on 2025-09-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vm_manager", "0004_container_resource_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcequota",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
