# Generated by Django 5.2.6 on 2025-10-04 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vm_manager", "0006_team_teammembership"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_type_name", models.CharField(max_length=512)),
                (
                    "memory_mb",
                    models.PositiveIntegerField(default=256, help_text="Memory in MB"),
                ),
                ("vcpus", models.PositiveIntegerField(default=2, help_text="vCPUs")),
                (
                    "disk_gib",
                    models.PositiveIntegerField(
                        default=10, help_text="Disk size in GiB"
                    ),
                ),
                (
                    "credits_cost",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Credits required to create/run this container type",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="resourcequota",
            name="default_disk_gib",
        ),
        migrations.RemoveField(
            model_name="resourcequota",
            name="max_containers",
        ),
        migrations.RemoveField(
            model_name="resourcequota",
            name="max_memory_mb",
        ),
        migrations.RemoveField(
            model_name="resourcequota",
            name="vcpus",
        ),
        migrations.AddField(
            model_name="resourcequota",
            name="credits",
            field=models.PositiveIntegerField(
                default=3, help_text="Total credits available to allocate to containers"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="container_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Selected container type; may be null for legacy containers",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="containers",
                to="vm_manager.containertype",
            ),
        ),
        migrations.AddField(
            model_name="resourcequota",
            name="allowed_types",
            field=models.ManyToManyField(
                blank=True, related_name="quotas", to="vm_manager.containertype"
            ),
        ),
    ]
