# Generated by Django 5.2.6 on 2025-10-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vm_manager",
            "0007_containertype_remove_resourcequota_default_disk_gib_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="containertype",
            name="private",
            field=models.BooleanField(default=False),
        ),
    ]
