# Generated by Django 5.2.6 on 2026-06-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vm_manager", "0008_containertype_private"),
    ]

    operations = [
        migrations.AlterField(
            model_name="containertype",
            name="private",
            field=models.BooleanField(
                default=False,
                help_text="If true, do not auto-assign to new user quotas",
            ),
        ),
    ]
