# Generated by Django 5.2.6 on 2026-06-10 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vm_manager", "0009_alter_containertype_private"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="is_pool",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True while the VM sits in the warm pool, unclaimed by a real user",
            ),
        ),
        migrations.AddField(
            model_name="containertype",
            name="pool_target",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of warm VMs of this type to keep ready per healthy node (only when poolable is true).",
            ),
        ),
        migrations.AddField(
            model_name="containertype",
            name="poolable",
            field=models.BooleanField(
                default=False,
                help_text="If true, this type may be pre-warmed in the warm pool. Heavy types should stay false so they are never pre-built.",
            ),
        ),
        migrations.AddIndex(
            model_name="container",
            index=models.Index(
                fields=["is_pool", "status", "container_type"],
                name="vm_manager__is_pool_17b7f2_idx",
            ),
        ),
    ]
