# Generated by Django 5.2.6 on 2026-06-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vm_manager", "0011_warm_pool_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="When set, the TTL reaper destroys this container after this time. Null means persistent. Used by ephemeral API runs.",
                null=True,
            ),
        ),
    ]
