# Generated by Django 5.2.6 on 2026-07-06 05:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vm_manager", "0015_delete_team_teammembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Collaborators granted access to this container. They can use the VM (IDE, terminal, AI, power on/off, restart, duplicate, files) but cannot rename it, delete it, or manage this list — only the owner (``user``) can. Credits always accrue to the owner.",
                related_name="shared_containers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
