# Generated by Django 5.2.2 on 2025-06-08 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docker_manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "max_containers",
                    models.PositiveIntegerField(
                        default=1, help_text="Número máximo de contenedores simultáneos"
                    ),
                ),
                (
                    "max_memory_mb",
                    models.PositiveIntegerField(
                        default=256, help_text="Memoria máxima por contenedor en MB"
                    ),
                ),
                (
                    "max_cpu_percent",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="CPU máxima por contenedor (como porcentaje)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="Cuota de recursos para este usuario",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quota",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
