# Generated by Django 5.2.5 on 2025-08-23 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docker_manager", "0003_filetemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filetemplate",
            name="files",
        ),
        migrations.CreateModel(
            name="FileTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=512)),
                ("content", models.TextField(blank=True, default="")),
                ("mode", models.PositiveIntegerField(default=420)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="docker_manager.filetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "path"),
                "unique_together": {("template", "path")},
            },
        ),
    ]
