# Generated by Django 5.2.6 on 2025-09-09 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField(blank=True, default="")),
                ("response", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="internal_co_user_id_5301ed_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("container.create", "Container create"),
                            ("container.destroy", "Container destroy"),
                            ("container.power_on", "Container power_on"),
                            ("container.power_off", "Container power_off"),
                            ("container.restart_shell", "Container restart_shell"),
                            ("container.send_command", "Container send_command"),
                            ("container.read_file", "Container read_file"),
                            ("container.write_file", "Container write_file"),
                            ("container.upload_file", "Container upload_file"),
                            ("container.list_dir", "Container list_dir"),
                            ("container.create_dir", "Container create_dir"),
                            ("container.real_status", "Container real_status"),
                            ("template.apply", "Template apply"),
                            ("user.info", "User Info"),
                            ("ws.connect", "WS Connect"),
                            ("ws.disconnect", "WS Disconnect"),
                            ("ws.restart", "WS Restart"),
                            ("ws.cmd", "WS Cmd"),
                            ("ws.ctrlc", "WS Ctrlc"),
                            ("ws.ctrld", "WS Ctrld"),
                            ("ws.clear", "WS Clear"),
                            ("ws.unknown", "WS Unknown"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                ("message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="internal_co_created_5ca2c3_idx"
                    ),
                    models.Index(
                        fields=["action"], name="internal_co_action_f6595e_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="internal_co_target__dfb1d1_idx",
                    ),
                ],
            },
        ),
    ]
