# Generated by Django 5.2.6 on 2025-09-19 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal_config", "0003_aimemory"),
        ("vm_manager", "0004_container_resource_quota"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusagelog",
            name="container",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="r_container",
                to="vm_manager.container",
            ),
        ),
    ]
