# Generated by Django 5.2.6 on 2025-09-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internal_config", "0004_aiusagelog_container"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("container.create", "Container create"),
                    ("container.destroy", "Container destroy"),
                    ("container.power_on", "Container power_on"),
                    ("container.power_off", "Container power_off"),
                    ("container.restart_shell", "Container restart_shell"),
                    ("container.send_command", "Container send_command"),
                    ("container.read_file", "Container read_file"),
                    ("container.write_file", "Container write_file"),
                    ("container.upload_file", "Container upload_file"),
                    ("container.list_dir", "Container list_dir"),
                    ("container.create_dir", "Container create_dir"),
                    ("container.real_status", "Container real_status"),
                    ("container.delete_file", "Container delete_file"),
                    ("container.change_path", "Container change_path"),
                    ("template.apply", "Template apply"),
                    ("user.info", "User Info"),
                    ("ws.connect", "WS Connect"),
                    ("ws.disconnect", "WS Disconnect"),
                    ("ws.restart", "WS Restart"),
                    ("ws.cmd", "WS Cmd"),
                    ("ws.ctrlc", "WS Ctrlc"),
                    ("ws.ctrld", "WS Ctrld"),
                    ("ws.clear", "WS Clear"),
                    ("ws.unknown", "WS Unknown"),
                    ("agent_tool.read_workspace", "Agent tool read_workspace"),
                    ("agent_tool.create_file", "Agent tool create_file"),
                    ("agent_tool.read_file", "Agent tool read_file"),
                    (
                        "agent_tool.create_full_project",
                        "Agent tool create_full_project",
                    ),
                    ("agent_tool.exec_command", "Agent tool exec_command"),
                    ("agent_tool.search", "Agent tool search"),
                    ("agent_tool.search_on_internet", "Agent tool search_on_internet"),
                    ("agent_tool.read_from_internet", "Agent tool read_from_internet"),
                ],
                max_length=64,
            ),
        ),
    ]
