# Generated by Django 5.2.6 on 2025-10-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internal_config", "0005_alter_auditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="aiusagelog",
            name="completion_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="Total output token used"
            ),
        ),
        migrations.AddField(
            model_name="aiusagelog",
            name="model_used",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="aiusagelog",
            name="prompt_tokens",
            field=models.PositiveIntegerField(
                default=0, help_text="Total input token used"
            ),
        ),
    ]
