# Generated by Django 5.2.6 on 2026-06-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "internal_config",
            "0006_aiusagelog_completion_tokens_aiusagelog_model_used_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aimemory",
            name="current_conversation",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
