# Generated by Django 5.2.6 on 2026-06-10 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human label for the key", max_length=128
                    ),
                ),
                (
                    "prefix",
                    models.CharField(
                        db_index=True,
                        help_text="Public, non-secret key id used to look the key up",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "hashed_key",
                    models.CharField(
                        help_text="sha256 of the secret; the secret is never stored",
                        max_length=64,
                    ),
                ),
                (
                    "scopes",
                    models.JSONField(
                        default=list,
                        help_text="Subset of read/exec/admin granted to this key",
                    ),
                ),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["prefix", "revoked"],
                        name="platform_ap_prefix_6e0764_idx",
                    )
                ],
            },
        ),
    ]
