# Generated by Django 5.2.5 on 2025-08-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docker_manager", "0002_resourcequota"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("files", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
