# Generated by Django 5.2.5 on 2025-08-29 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docker_manager", "0004_remove_filetemplate_files_filetemplateitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("container.create", "Container create"),
                            ("container.destroy", "Container destroy"),
                            ("container.power_on", "Container power_on"),
                            ("container.power_off", "Container power_off"),
                            ("container.restart_shell", "Container restart_shell"),
                            ("container.send_command", "Container send_command"),
                            ("container.read_file", "Container read_file"),
                            ("container.write_file", "Container write_file"),
                            ("container.upload_file", "Container upload_file"),
                            ("container.list_dir", "Container list_dir"),
                            ("container.create_dir", "Container create_dir"),
                            ("container.real_status", "Container real_status"),
                            ("template.apply", "Template apply"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                ("message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("success", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="docker_mana_created_e73c30_idx"
                    ),
                    models.Index(
                        fields=["action"], name="docker_mana_action_d3f5c3_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="docker_mana_target__22853a_idx",
                    ),
                ],
            },
        ),
    ]
