# Generated by Django 5.2.5 on 2025-08-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docker_manager", "0005_auditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("container.create", "Container create"),
                    ("container.destroy", "Container destroy"),
                    ("container.power_on", "Container power_on"),
                    ("container.power_off", "Container power_off"),
                    ("container.restart_shell", "Container restart_shell"),
                    ("container.send_command", "Container send_command"),
                    ("container.read_file", "Container read_file"),
                    ("container.write_file", "Container write_file"),
                    ("container.upload_file", "Container upload_file"),
                    ("container.list_dir", "Container list_dir"),
                    ("container.create_dir", "Container create_dir"),
                    ("container.real_status", "Container real_status"),
                    ("template.apply", "Template apply"),
                    ("user.info", "User Info"),
                    ("ws.connect", "WS Connect"),
                    ("ws.disconnect", "WS Disconnect"),
                    ("ws.restart", "WS Restart"),
                    ("ws.cmd", "WS Cmd"),
                    ("ws.ctrlc", "WS Ctrlc"),
                    ("ws.ctrld", "WS Ctrld"),
                    ("ws.clear", "WS Clear"),
                    ("ws.unknown", "WS Unknown"),
                ],
                max_length=64,
            ),
        ),
    ]
