# Generated by Django 5.2.5 on 2025-08-30 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docker_manager", "0006_alter_auditlog_action"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcequota",
            name="ai_use_per_day",
            field=models.PositiveIntegerField(
                default=5, help_text="Daily request for the AI"
            ),
        ),
        migrations.AlterField(
            model_name="resourcequota",
            name="max_containers",
            field=models.PositiveIntegerField(
                default=1, help_text="Max number of alive containers"
            ),
        ),
        migrations.AlterField(
            model_name="resourcequota",
            name="max_cpu_percent",
            field=models.PositiveIntegerField(
                default=20, help_text="Max CPU per container VCPU"
            ),
        ),
        migrations.AlterField(
            model_name="resourcequota",
            name="max_memory_mb",
            field=models.PositiveIntegerField(
                default=256, help_text="Max memory per container MB"
            ),
        ),
        migrations.AlterField(
            model_name="resourcequota",
            name="user",
            field=models.OneToOneField(
                help_text="Resource quota user",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quota",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="AIUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField(blank=True, default="")),
                ("response", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="docker_mana_user_id_d8d054_idx",
                    )
                ],
            },
        ),
    ]
