# Generated by Django 5.2.5 on 2025-09-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docker_manager", "0007_resourcequota_ai_use_per_day_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filetemplate",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
