# Generated by Django 5.2.5 on 2025-09-06 04:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docker_manager", "0008_filetemplate_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcequota",
            name="default_disk_gib",
            field=models.PositiveIntegerField(default=10, help_text="Max disk in gb"),
        ),
    ]
