# Generated by Django 5.2.5 on 2025-09-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("docker_manager", "0009_resourcequota_default_disk_gib"),
    ]

    operations = [
        migrations.AddField(
            model_name="container",
            name="disk_gib",
            field=models.PositiveIntegerField(default=10, help_text="disk in gb"),
        ),
        migrations.AddField(
            model_name="container",
            name="memory_mb",
            field=models.PositiveIntegerField(
                default=256, help_text="memory for the container"
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="vcpu",
            field=models.PositiveIntegerField(
                default=2, help_text="CPU for the container"
            ),
        ),
        migrations.AlterField(
            model_name="resourcequota",
            name="max_cpu_percent",
            field=models.PositiveIntegerField(
                default=2, help_text="Max CPU per container VCPU"
            ),
        ),
    ]
