services:
  web:
    build: ./web_service/.
    command: ./entrypoint.sh
    volumes:
      - ./web_service:/app
      - ./vm_data:/app/vm_data
      - /home/hector/.ssh/id_ed25519:/root/.ssh/id_vm_pequeroku:ro # CHANGE ME
      - /home/hector/.ssh/id_ed25519.pub:/root/.ssh/id_vm_pequeroku.pub:ro # CHANGE ME
    # devices:
    #   - /dev/kvm:/dev/kvm
    # security_opt:
    #   - seccomp=unconfined
    #   - apparmor:unconfined
    environment:
      VM_SSH_PRIVKEY: /root/.ssh/id_vm_pequeroku
      VM_SSH_USER: root
      VM_BASE_IMAGE: /app/vm_data/base/jammy-golden.qcow2
    networks:
      - pequeroku-net
  db:
    image: "postgres:16"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - .db_data:/var/lib/postgresql/data
    networks:
      - pequeroku-net

  nginx:
    image: nginx:latest
    container_name: nginx_static
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./front:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - pequeroku-net
    restart: unless-stopped

networks:
  pequeroku-net:
    external: false
